### ISSUE TITLE
Non-dev docs not deploying

### ISSUE THREAD

**Issue by mhauru** [TuringLang/AbstractMCMC.jl#140]
The docs page at https://turinglang.org/AbstractMCMC.jl only has the `dev` docs, no other releases, nor one for `stable`. This e.g. makes the `docs | stable` button in the README broken.

The documentation Action seems to run just fine when a new version tag is made and the `dev` docs are up to date, from when the last release was made. I wasn't able to quickly figure out what the problem is.

**Comment by shravanngoswamii** [comment]
Looks like CI doesn't run on tags. Probably a documenter ssh key missing in the repo settings.

**Comment by devmotion** [comment]
Missing keys are the most likely reason in my experience.

**Comment by devmotion** [comment]
I added DOCUMENTER_KEY (and a matching deploy key).

**Comment by penelopeysm** [comment]
Fixed now by the addition of the key and deployment of a new version :)
