### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/AbstractMCMC.jl#2]
@JuliaRegistrator register

**Comment by yebai** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
Looks like the automerger isn't happy that the package name [ends in a capital letter](https://github.com/JuliaRegistries/General/pull/5843#issuecomment-557932406) -- should we change the name or petition for an exception of some kind?

**Comment by yebai** [comment]
Sounds good to petition it, since it does not make a lot of sense to add a small letter here. 

Also, we can replace overloading `Distributions.sample` with `StatsBase.sample`. This change won't affect functionality, but allows us to (further) reduce the dependency footage here.

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by devmotion** [comment]
Can we register a new version or should we wait for https://github.com/TuringLang/AbstractMCMC.jl/pull/13? There are [quite many changes and fixes since the last release](https://github.com/TuringLang/AbstractMCMC.jl/compare/v0.3.0...master) that would be nice to make use of in MCMCChains (and all other downstream packages).

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register

**Comment by devmotion** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
@JuliaRegistrator register
