### ISSUE TITLE
default_convergence

### ISSUE THREAD

**Issue by mileslucas** [TuringLang/AbstractMCMC.jl#25]
I propose to add something like 
```julia
default_convergence(::S) where {S<:AbstractSampler} = default_convergence(S)
default_convergence(::Type{<:AbstractSampler}) = error(...)
```
and change the `sample` method for convergence sampling to look like 
```julia
s::AbstractSampler,
is_done=default_convergence(s);
```

This is kind of an in-between of having a `done_sampling` method that users _must_ override and the current no-default function argument passing.

For an example of what this would look like in `NestedSamplers.jl`:
```julia
import AbstractMCMC: default_convergence

default_convergence(Nested) = dlogz_convergence
```

**Comment by devmotion** [comment]
What would be the advantage over just specifying a default positional argument for your sampler? You can already define
```julia
sample(rng::AbstractRNG, model::MyModel, sampler::MySampler; kwargs...) = sample(rng, model, sampler, default_convergence; kwargs...)
```
And if needed, you could even base `default_convergence` on `sampler` (BTW as mentioned in the Julia docs, I suggest defining `default_convergence`  either for types or instances of samplers but not both).

However, I think the more general problem that I've experienced myself in EllipticalSliceSampling and Turing is that currently there's no easy way of changing default keyword arguments apart from reimplementing `sample` and `psample`. IMO `sample` and `psample` implementation in AbstractMCMC should be forwarded to some internal method. Then one could reuse the default algorithm but easily change the default arguments or force some settings. I'll make a PR.

**Comment by mileslucas** [comment]
Yeah, your pain point is exactly why I opened this. If I want to add the default I end up having to either reimplement (read: copy paste) the version Cameron has written with one line change. Or else, I run into issues because the current way of having the optional rng ends up accidentally being overwritten by any non-rgb method I write (because the third arg for both the sample calls is Any). 

Thanks for taking on a PR. I look forward to it!

**Comment by devmotion** [comment]
Do you think the additional flexibility that `mcmcsample` and `mcmcpsample` provide solves your issue?

**Comment by mileslucas** [comment]
It does solve it and provides more overall flexibility. My solution with a trait-like function would be more appropriate if we built in traits to samplers (ie SampleStyle(::Nested) = Convergence())
