### ISSUE TITLE
Unnecessary copies in multi-threaded parallel sampling

### ISSUE THREAD

**Issue by xukai92** [TuringLang/AbstractMCMC.jl#37]
The following lines 

https://github.com/TuringLang/AbstractMCMC.jl/blob/master/src/sample.jl#L206-L208

could give unused copies if the number of threads is larget than the specified number of chains.

**Comment by devmotion** [comment]
Unfortunately, I don't think this can be fixed by us (see https://github.com/TuringLang/AbstractMCMC.jl/pull/38#issuecomment-629605149).
