### ISSUE TITLE
Documentation on role of AbstractModel instances for MCMC

### ISSUE THREAD

**Issue by felipegssantos** [TuringLang/AbstractMCMC.jl#54]
I took some time reading through the codebase, including the unit tests, in order to get a grasp of what the intended use of AbstractModel instances is during sampling. Could anyone help me understand this? I am willing to contribute with new documentation once I get this.

Trying to give a more specific example: I want to leverage this package in my MCMC simulations, though without the whole Turing - in particular, my use case does not seem to benefit from a PPL.

**Comment by cpfiffer** [comment]
The use of `AbstractModel` is generally to be some kind of something that returns a log density given a parameterization. For example, [`AdvancedMH`](https://github.com/TuringLang/AdvancedMH.jl) implements essentially just a function wrapper:

https://github.com/TuringLang/AdvancedMH.jl/blob/570e78018c3a411bfe634e98207ac4c0c0874ea7/src/AdvancedMH.jl#L37

Ultimately it's up to you what that looks like -- what's your exact use case?

**Comment by devmotion** [comment]
https://github.com/TuringLang/EllipticalSliceSampling.jl is another example of a package that uses AbstractMCMC without Turing. Here the model is just a struct of the prior and the log-likelihood: https://github.com/TuringLang/EllipticalSliceSampling.jl/blob/master/src/model.jl

**Comment by felipegssantos** [comment]
I want to generate samples for a discrete distribution of the form `p(S::Vector{T}) = exp(-f(S))/Z` (an [Ising model](https://en.wikipedia.org/wiki/Ising_model), for example). More specifically, I want to look at the distribution of some scalar functions of this `S` vector.

The way I see it, I could just implement the `step` method for my specific subtype of `AbstractSampler` (which would carry in it, say, a Metropolis-Hastings logic for generating samples). Assuming that I understood correctly, I do not see any use for an `AbstractModel`. Taking the `AdvancedMH` example, I could not find in the implementation how these `DensityModel`s are actually used.

**Comment by cpfiffer** [comment]
`DensityModels` are used here:

https://github.com/TuringLang/AdvancedMH.jl/blob/570e78018c3a411bfe634e98207ac4c0c0874ea7/src/mh-core.jl#L223

**Comment by felipegssantos** [comment]
Ok, now I got it. Thank you. In `AdvancedMH` it's really just any kind of model with a log density such that it can be used any way you want inside the `step` method.

But, taking this usage into account, I feel like the `AbstractModel`'s docstrings do not do it enough justice. Currently it says:
> An `AbstractModel` represents a generic model type that can be used to perform inference.
But in `AdvancedMH` you are not technically "performing inference" using this model. Moreover, I don't even need the model to be an actual density - it could be anything I want, provided it can calculate something when given the parameters. In my example, the model can just return `exp(-f(S)` without worrying about the normalization constant `Z` - or even `f(S)`, provided my `step` method does what it must.

If what I said makes sense, it would be nice to extend these docstrings to reflect this kind of usage.

**Comment by cpfiffer** [comment]
How is that not performing inference?

**Comment by felipegssantos** [comment]
`AdvancedMH` is using the model interface to implement part of the sampling logic. That is not performing inference because sampling and inference are not the same thing.

Why do you think it is performing inference?

**Comment by cpfiffer** [comment]
Because at the end you receive a posterior of your parameters. That seems an awful lot like inference to me.

**Comment by felipegssantos** [comment]
I do not have parameters in my use case. I have hyperparameters, a complex distribution and want to generate samples.

**Comment by felipegssantos** [comment]
There is no posterior involved. No bayesian reasoning. Just samples from a distribution. It just does not matter how I ended up at this distribution for Monte Carlo. All that matters is having a distribution hard to sample from.

**Comment by cpfiffer** [comment]
Inference does not require "bayesian reasoning". It is a very broad term. Maximum likelihood is inference. The simple mean is a form of inference. It is a very, very broad term, and I suspect you and I have different understandings of what "inference" is.

> I do not have parameters in my use case. I have hyperparameters, a complex distribution and want to generate samples.

This makes no sense. If you only have hyperparameters, you have only regular parameters. Hyperparameters for a distribution with no sub-parameters are the parameters for the complex distribution. If you are drawing from that distribution, you are performing inference on whatever your outcome with respect to those hyperparameters.

**Comment by felipegssantos** [comment]
I could answer point by point why [this answer](https://github.com/TuringLang/AbstractMCMC.jl/issues/54#issuecomment-784574605) is totally inadequate but I won't. This discussion is leading nowhere. I still believe the type's docstrings are confusing and conceptually problematic, but I'm not willing to contribute anymore. So I'm closing the issue.
