### ISSUE TITLE
Update convergence sampling signature to use `state`

### ISSUE THREAD

**Issue by mileslucas** [TuringLang/AbstractMCMC.jl#67]
https://github.com/TuringLang/AbstractMCMC.jl/blob/d961513b0ad3dc53d414da6581b332b66c4d0ef3/src/sample.jl#L209

I think this should be updated to be
```julia
isdone(rng, model, sampler, samples, state, i; progress=progress, kwargs...)
```
to coincide with the immutable samplers (#42, #56), which would be breaking (unfortunately).

Thoughts on this? I'm happy to PR, just let me know if this has downstream effects that I'll need to address, too.

**Comment by devmotion** [comment]
I would be fine with adding it, it seems reasonable (even though I don't think that the linked PRs imply that one has to do it). As long as we follow semver and make a breaking release we should not worry about downstream packages here I think (additionally, I believe it's not used in many downstream packages).
