### ISSUE TITLE
Standard InferenceData-like API

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/AbstractMCMC.jl#74]
I think it would be great to have some kind of struct that behaves like ArviZ's InferenceData objects and lets you wrap a lot of different results in a nice little bundle.

**Comment by cpfiffer** [comment]
The equivalent is any chains object that implements the AbstractMCMC interface. AbstractMCMC is a very general interface for sampling, not the actual storage struct.

The most feature-rich example of this is [MCMCChains](https://github.com/TuringLang/MCMCChains.jl).
